---
title: "Git Demo"
author: "Saurabh Khanna"
date: "[`r format(Sys.Date(), format='%B %d, %Y')`]"
output: 
  github_document:
    toc: true
---


```{r setup, include=FALSE}
# knitr options
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, fig.retina = 4)
```


```{r message=FALSE, warning=FALSE}
# Libraries
pacman::p_load(tidyverse, janitor, hrbrthemes)
```

## Scanning the data

```{r}
df <- read_csv("ojs-data.csv")
df %>% arrange(desc(total_record_count)) %>% glimpse()
```


## Articles published

```{r, eval= T}
total_records <-
  df %>%
  select(record_count_2010:record_count_2021) %>% 
  pivot_longer(cols = starts_with("record_count")) %>% 
  mutate(
    name = parse_number(name)
  ) %>% 
  group_by(name) %>% 
  summarize(value = sum(value, na.rm = T)) %>% 
  summarize_all(sum) %>% 
  pull(value)


```

Total articles published till date: __`r format(total_records, big.mark = ",", scientific = FALSE)`__


```{r, fig.retina=4, out.width="100%", eval=T}
df %>%
  select(record_count_2010:record_count_2021) %>% 
  pivot_longer(cols = starts_with("record_count")) %>% 
  mutate(
    name = parse_number(name)
  ) %>% 
  group_by(name) %>% 
  summarize(value = sum(value, na.rm = T)) %>%
  ggplot(aes(name, value)) +
  geom_col(fill = "#091f5e", alpha = 0.8) +
  #geom_point() +
  #geom_line() +
  scale_x_continuous(breaks = seq(2010, 2021, 1)) +
  scale_y_continuous(labels = scales::label_number_si()) +
  theme_ipsum() +
  labs(
    x = "Year",
    y = "Articles per year",
    title = "Articles published per year in OJS journals",
    subtitle = "6.2 million articles published since 2010"
  )
```
